# Workflow names are optional, but should be provided.
# They are displayed on GitHub when the action is run.
name: Build ✨

# The `on` property configures the events that will trigger the workflow.
# In our case we want it to run when the `pull_request` event is triggered.
# In short, that means that the workflow will run when a pull request is
# either opened or updated (but not renamed or labeled – code needs to
# be changed).
on:
  - pull_request

# Jobs are what actually do the work. We can add as many jobs as we want.
# These will be run in parallel.
jobs:
  build:
    # As with workflow names (and even step names), job names are not
    # strictly required, but they are good practice.
    name: Build

    # There are many virtual machines we can run our jobs on. The most
    # common one is `ubuntu-latest`. See this page for a full list of
    # officially supported runners: https://github.com/actions/runner-images
    runs-on: ubuntu-latest

    # Each job can have multiple steps. These will be run in sequence.
    steps:
      - name: Checkout repository
        # To reference external workflows, we use the `uses` keyword.
        # The thing after the `@` is the version of the workflow, and
        # references a Git tag.
        uses: actions/checkout@v4
      - name: npm install
        run: npm ci
      - name: npm build
        run: npm run build
  test:
    # As with workflow names (and even step names), job names are not
    # strictly required, but they are good practice.
    name: TEST

    # There are many virtual machines we can run our jobs on. The most
    # common one is `ubuntu-latest`. See this page for a full list of
    # officially supported runners: https://github.com/actions/runner-images
    runs-on: ubuntu-latest

    # Each job can have multiple steps. These will be run in sequence.
    steps:
      - name: Checkout repository
        # To reference external workflows, we use the `uses` keyword.
        # The thing after the `@` is the version of the workflow, and
        # references a Git tag.
        uses: actions/checkout@v4
      - name: npm install
        run: npm ci
      - name: npm build
        run: npm run build
      - name: npm test
        run: npm run test
  lint:
    # As with workflow names (and even step names), job names are not
    # strictly required, but they are good practice.
    name: LINT

    # There are many virtual machines we can run our jobs on. The most
    # common one is `ubuntu-latest`. See this page for a full list of
    # officially supported runners: https://github.com/actions/runner-images
    runs-on: ubuntu-latest

    # Each job can have multiple steps. These will be run in sequence.
    steps:
      - name: Checkout repository
        # To reference external workflows, we use the `uses` keyword.
        # The thing after the `@` is the version of the workflow, and
        # references a Git tag.
        uses: actions/checkout@v4
      - name: npm install
        run: npm ci
      - name: npm build
        run: npm run build
      - name: npm lint
        run: npm run lint:check
  post-comment:
    runs-on: ubuntu-latest

    needs: [test, lint]

    steps:
      - name: Post comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            All jobs have finished! 🎉
